version: '2'
catalog:
  name: "Rancher-LB"
  version: "v1.0"
  description: "Load Balancer"
services:
  external:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      default_cert: ${default_cert}
      port_rules:
      - hostname: ${git_service}
        priority: 1
        protocol: http
        service: ${gitlab_service_name}
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000